language: bash
services: docker

env:
  - VARIANT=latest

before_install:
  - env | sort
  - image="backslide:${VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
